### ISSUE TITLE
Share dialog in new tab doesn't close upon saving

### ISSUE THREAD

**Issue by philippe-git** [bufferapp/buffer-firefox#18]
When the share dialog opens in a new tab, it then fails closing after the post is saved: "Scripts may not close windows that were not opened by script."

Let's double-check the opener and closer, and make sure they're the same.

Original report: https://bugzilla.mozilla.org/show_bug.cgi?id=1059855#c43

**Comment by pioul** [comment]
Had a quick look today:

- On Chrome, we can open tabs from privileged code (background scripts) and then close this tab with `window.close()` from a script straight inside this tab
- In Firefox, that's not possible : in this scenario, "Scripts may not close windows that were not opened by script."
- Either the opener or the closer has to be changed as a result:
  - In Firefox, calling `window.open()` from a content script doesn't work (triggers the popup blocker), as expected since after going through page-extension messages, the origin of the click has been lost, and it's hard to tell for the browser whether or not the call to `window.open()` follows a genuine user click
  - Still, the same works in Chrome, but that's no help here for Firefox

**Comment by philippe-git** [comment]
Had a quick look today:

- On Chrome, we can open tabs from privileged code (background scripts) and then close this tab with `window.close()` from a script straight inside this tab
- In Firefox, that's not possible : in this scenario, "Scripts may not close windows that were not opened by script."
- Either the opener or the closer has to be changed as a result:
  - In Firefox, calling `window.open()` from a content script doesn't work (triggers the popup blocker), as expected since after going through page-extension messages, the origin of the click has been lost, and it's hard to tell for the browser whether or not the call to `window.open()` follows a genuine user click

    Still, the same works in Chrome, but that's no help here for Firefox, which seems to have a tougher opener/closer policy than Chrome when it comes to extensions

  - The last solution is to refactor the Chrome/Firefox extension a bit so that we do both the opening and closing from privileged code.

I'll spend some more time on that last solution ↑ next week

**Comment by philippe-git** [comment]
This was fixed in https://github.com/bufferapp/buffer-extension-shared/commit/0dca81fbd513f3a5c2545cb0a7826f8f1fa35752 and https://github.com/bufferapp/buffer-chrome/commit/b5e7612c8a228d4abc8578a3653bbcedc8c6e4c7 by opening + closing tabs from privileged code :)
